# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'number_ocr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_number_ocr(object):
    def setupUi(self, number_ocr):
        number_ocr.setObjectName("number_ocr")
        number_ocr.setEnabled(True)
        number_ocr.resize(908, 577)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        number_ocr.setFont(font)
        self.imageButton = QtWidgets.QPushButton(number_ocr)
        self.imageButton.setGeometry(QtCore.QRect(10, 110, 121, 51))
        self.imageButton.setObjectName("imageButton")
        self.ocrButton = QtWidgets.QPushButton(number_ocr)
        self.ocrButton.setGeometry(QtCore.QRect(10, 170, 121, 51))
        self.ocrButton.setObjectName("ocrButton")
        self.imageBrowser = QtWidgets.QLabel(number_ocr)
        self.imageBrowser.setGeometry(QtCore.QRect(300, 50, 541, 321))
        self.imageBrowser.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.imageBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.imageBrowser.setLineWidth(2)
        self.imageBrowser.setObjectName("imageBrowser")
        self.label = QtWidgets.QLabel(number_ocr)
        self.label.setGeometry(QtCore.QRect(520, 390, 141, 61))
        self.label.setObjectName("label")
        self.numberBrowser = QtWidgets.QTextBrowser(number_ocr)
        self.numberBrowser.setGeometry(QtCore.QRect(300, 450, 541, 91))
        self.numberBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.numberBrowser.setLineWidth(2)
        self.numberBrowser.setObjectName("numberBrowser")
        self.pushButton = QtWidgets.QPushButton(number_ocr)
        self.pushButton.setGeometry(QtCore.QRect(150, 110, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(number_ocr)
        self.label_2.setGeometry(QtCore.QRect(110, 240, 101, 51))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(number_ocr)
        self.textBrowser.setGeometry(QtCore.QRect(20, 290, 256, 251))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(number_ocr)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 121, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(number_ocr)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 170, 121, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(number_ocr)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 50, 121, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.imageButton.clicked.connect(self.slot_open_image)#选择图片
        self.ocrButton.clicked.connect(self.slot_output_digital)##识别
        self.pushButton.clicked.connect(self.photograph)#拍照
        self.pushButton_2.clicked.connect(self.start_thread)#开启进程
        self.pushButton_3.clicked.connect(self.send_data)#发送数据
        self.pushButton_4.clicked.connect(self.close_thread)#关闭进程
        self.retranslateUi(number_ocr)
        QtCore.QMetaObject.connectSlotsByName(number_ocr)

    def retranslateUi(self, number_ocr):
        _translate = QtCore.QCoreApplication.translate
        number_ocr.setWindowTitle(_translate("number_ocr", "相机数据处理辅助工具"))
        self.imageButton.setText(_translate("number_ocr", "选择图片"))
        self.ocrButton.setText(_translate("number_ocr", "开始识别"))
        self.label.setText(_translate("number_ocr", "识别结果"))
        self.pushButton.setText(_translate("number_ocr", "拍照"))
        self.label_2.setText(_translate("number_ocr", "进程"))
        self.pushButton_2.setText(_translate("number_ocr", "启动线程"))
        self.pushButton_3.setText(_translate("number_ocr", "发送数据"))
        self.pushButton_4.setText(_translate("number_ocr", "关闭线程"))
